services:
    mongo:
        image: mongo
        container_name: mongo
        env_file:
            - ./.env.mongo
        ports:
          - "127.0.0.1:27017:27017"
        volumes:
          - quest-data:/data/db
        networks:
          - n8n_network
          - mongo-data-network
    
    mongo-express:
        image: mongo-express
        container_name: quest_mongo_express
        profiles:
            - quest-express
        ports:
            - "127.0.0.1:8081:8081"
        
        env_file:
            - ./.env.mongo-express
        depends_on:
            - mongo
        networks:
            - mongo-data-network


volumes:
    piston_data:
        external: true
    quest-data:
        external : true

networks:
    n8n_network:
        external: true
    quest:
        external: true
    mongo-data-network:
        external: true
    piston: