services:

  backend:
    container_name: expense-tracker-backend
    restart: always
    build: 
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
        [expense-tracker]

  frontend:
    container_name: expense-tracker-frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
        [expense-tracker]

networks:
    expense-tracker:
        external: true