FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies (only required ones)
RUN npm install

# Copy application code
COPY . .

EXPOSE 5000

# Start the server
CMD ["node", "server.js"]
